/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hand_handweight_loadJNI_loadJNI */
#include <stdio.h>
#include <stdlib.h>

#include <math.h>
#include <stddef.h>
#include <string.h>
#include "rtwtypes.h"

#include "rt_nonfinite.h"
#include "stableWeightPredict_types.h"
#ifndef _Included_cn_hand_tech_loadJNI_loadJNI
#define _Included_cn_hand_tech_loadJNI_loadJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_hand_tech_loadJNI_loadJNI
 * Method:    getWeight
 * Signature: ([D[D[DDLcn/hand/tech/loadJNI/CanshuBean;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_hand_tech_loadJNI_loadJNI_getWeight
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jobject);

#ifdef __cplusplus
}
#endif
#endif
