/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hand_handweight_loadJNI_loadJNI */
#include <stdio.h>
#include <stdlib.h>

#include <math.h>
#include <stddef.h>
#include <string.h>
#include "rtwtypes.h"
#include <android/log.h>
#include <errno.h>

#include "rt_nonfinite.h"
#include "stableWeightPredict.h"
#include "stableWeightPredict_terminate.h"
#include "stableWeightPredict_initialize.h"
#ifndef _Included_cn_hand_tech_loadJNI_loadJNI
#define _Included_cn_hand_tech_loadJNI_loadJNI

#define TAG "jni调试测试重量" // 这个是自定义的LOG的标识
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,TAG,__VA_ARGS__) // 定义LOGE类型
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,TAG,__VA_ARGS__)

#ifdef __cplusplus
extern "C" {
#endif



double status_flag = 0;
double locked_weight = 0;
double stable_counter = 0;
double last_weight = 0;


double last_data1=0;
double last_data2=0;
double last_data3=0;
double last_data4=0;
double last_data5=0;
double last_data6=0;
double last_data7=0;
double last_data8=0;
double last_data9=0;
double last_data10=0;
double last_data11=0;
double last_data12=0;
double last_data13=0;
double last_data14=0;
double last_data15=0;
double last_data16=0;
double last_data17=0;
double last_data18=0;
double last_data19=0;
double last_data20=0;
double last_data21=0;
double last_data22=0;
double last_data23=0;
double last_data24=0;
double last_data25=0;
double last_data26=0;
double last_data27=0;
double last_data28=0;
double last_data29=0;
double last_data30=0;
double last_data31=0;
double last_data32=0;
double last_data33=0;
double last_data34=0;
double last_data35=0;
double last_data36=0;
double last_data37=0;
double last_data38=0;
double last_data39=0;
double last_data40=0;
double last_data41=0;
double last_data42=0;
 struct0_T  st0={0};//用全局变量 解决 内存溢出问题
 struct1_T  st1={0};

 void st1_to_st0(struct0_T* st0,struct1_T*st1)
 {
   int i;
   if(st0==NULL || st1==NULL)
    return;
   //X_input
   for(i=0;i<1400000;i++)
    st0->KNN_Model.X_input[i]=st1->X_input[i];
     LOGI("******************X_input:%d",st1->X_input[0]);
   //Y_input
   for(i=0;i<100000;i++)
   st0->KNN_Model.Y_input[i]=st1->Y_input[i];
    LOGI("******************Y_input:%d",st1->Y_input[0]);
   //Mu
   for(i=0;i<14;i++)
   st0->KNN_Model.Mu[i]=st1->Mu[i];
    LOGI("******************Mu:%d",st1->Mu[0]);
   //Sigma
    for(i=0;i<14;i++)
    st0->KNN_Model.Sigma[i]=st1->Sigma[i];
     LOGI("******************Sigma:%d",st1->Sigma[0]);
 }
/*
 * Class:     com_hand_handweight_loadJNI_loadJNI
 * Method:    getWeight
 * Signature: ([D[D[DDLcn/hand/tech/loadJNI/CanshuBean;)D
 */
JNIEXPORT jdouble JNICALL  Java_cn_hand_tech_loadJNI_loadJNI_getWeight
  (JNIEnv *env, jclass jz, jdoubleArray Sensor_data,jdoubleArray x_input,jdoubleArray y_input, jdouble clear_flag, jobject csbean){


            if(NULL== env){
             return 0;
            }
            LOGI("******************Java_cn_hand_tech_loadJNI_loadJNI_getWeight:%d",errno);


            jdouble * arr_Sensor_data= (*env)->GetDoubleArrayElements(env,Sensor_data,NULL);

            LOGI("******************arr_Sensor_data:%d",arr_Sensor_data);

            jclass bigClass = (*env)->FindClass(env, "cn/hand/tech/loadJNI/CanshuBean");
                LOGI("******************bigClass:%d",bigClass);

             jfieldID X_input     = (*env)->GetFieldID(env, bigClass, "X_input" , "[D");
             jfieldID Y_input     = (*env)->GetFieldID(env, bigClass, "Y_input"   , "[D");
             jfieldID Mu         = (*env)->GetFieldID(env, bigClass, "Mu", "[D");
             jfieldID Sigma   = (*env)->GetFieldID(env, bigClass, "Sigma", "[D");
                LOGI("******************Sigma:%d",Sigma);


              int  xlen =(*env)->GetArrayLength(env,x_input);
              LOGI("******************xlen:%d",xlen);

                double *chArr =(double *) (*env)->GetDoubleArrayElements(env,x_input, NULL);
               // double *szStrBuf =(double *)malloc(xlen*2+10);//申请内存
               // memset(szStrBuf, 0, xlen*2+10); //内存初始化
               // memcpy((void*)&st1.X_input, (void*)chArr, xlen);
                LOGI("******************chArr:%d",chArr);
                for(int p=0;p<xlen;p++){
                 st1.X_input[p]=chArr[p];
                }
              // (*env)->SetDoubleArrayRegion(env,st1.X_input,0,xlen,chArr);
              (*env)->ReleaseDoubleArrayElements(env, x_input, chArr,0);


              int  ylen = (*env)->GetArrayLength(env,y_input);
               double *chArry =(double *) (*env)->GetDoubleArrayElements(env,y_input, NULL);
               // double *szStrBuf1 =(double *)malloc(ylen*2+10);//申请内存
                // memset(szStrBuf1, 0, ylen*2+10); //内存初始化
               //  if(NULL==szStrBuf1){
               //   LOGI("******************szStrBuf1:%d","失败");
               //  }
               // memcpy(st1.Y_input, chArry, ylen);
                for(int p1=0;p1<ylen;p1++){
                 st1.Y_input[p1]=chArry[p1];
               }
                //  (*env)->SetDoubleArrayRegion(env,st1.Y_input,0,ylen,chArry);
                 (*env)->ReleaseDoubleArrayElements(env, y_input, chArry,0);
                   LOGI("******************y_input:%d",ylen);

              jdoubleArray mu1 = (jdoubleArray)(*env)->GetObjectField(env, csbean, Mu);//获取数据

              int  mlen = (*env)->GetArrayLength(env,mu1);
              double *mm = (double *)(*env)->GetDoubleArrayElements(env,mu1, NULL);
                  for(int p2=0;p2<mlen;p2++){
                      st1.Mu[p2]=mm[p2];
                 }
                  LOGI("******************Mu:%d",mlen);
                 (*env)->ReleaseDoubleArrayElements(env, mu1, mm,0);

              jdoubleArray sigma1 = (jdoubleArray)(*env)->GetObjectField(env, csbean, Sigma);//获取数据

                int  slen = (*env)->GetArrayLength(env,sigma1);
                double *ss = (double *)(*env)->GetDoubleArrayElements(env,sigma1, NULL);
                LOGI("******************sigma:%d",slen);
                for(int p3=0;p3<slen;p3++){
                     st1.Sigma[p3]=ss[p3];
               }
                  (*env)->ReleaseDoubleArrayElements(env, sigma1, ss,0);

            jfieldID sensor_sel_for_loc     = (*env)->GetFieldID(env, bigClass, "sensor_sel_for_loc" , "[D");
             jfieldID LR_model_adj_stage_bound_input   = (*env)->GetFieldID(env, bigClass, "LR_model_adj_stage_bound_input" , "[D");
            jfieldID LR_model_adj_stage_bound   = (*env)->GetFieldID(env, bigClass, "LR_model_adj_stage_bound" , "[D");

            jfieldID LR_model_adj_sensors1   = (*env)->GetFieldID(env, bigClass, "LR_model_adj_sensors1", "[D");
            jfieldID LR_model_adj_sensors2   = (*env)->GetFieldID(env, bigClass, "LR_model_adj_sensors2", "[D");
            jfieldID LR_model_adj_sensors3   = (*env)->GetFieldID(env, bigClass, "LR_model_adj_sensors3", "[D");
            jfieldID LR_model_adj_sensors4   = (*env)->GetFieldID(env, bigClass, "LR_model_adj_sensors4", "[D");
            jfieldID LR_model_adj_sensors5   = (*env)->GetFieldID(env, bigClass, "LR_model_adj_sensors5", "[D");
            jfieldID LR_model_adj_sensors6   = (*env)->GetFieldID(env, bigClass, "LR_model_adj_sensors6", "[D");
            jfieldID LR_model_adj_sensors7   = (*env)->GetFieldID(env, bigClass, "LR_model_adj_sensors7", "[D");
            jfieldID LR_model_adj_sensors8   = (*env)->GetFieldID(env, bigClass, "LR_model_adj_sensors8", "[D");
            jfieldID LR_model_adj_sensors9   = (*env)->GetFieldID(env, bigClass, "LR_model_adj_sensors9", "[D");
            jfieldID LR_model_adj1_input   = (*env)->GetFieldID(env, bigClass, "LR_model_adj1_input", "[D");
            jfieldID LR_model_adj2_input   = (*env)->GetFieldID(env, bigClass, "LR_model_adj2_input", "[D");
            jfieldID LR_model_adj3_input   = (*env)->GetFieldID(env, bigClass, "LR_model_adj3_input", "[D");
            jfieldID LR_model_adj4_input   = (*env)->GetFieldID(env, bigClass, "LR_model_adj4_input", "[D");
            jfieldID LR_model_adj5_input   = (*env)->GetFieldID(env, bigClass, "LR_model_adj5_input", "[D");
            jfieldID LR_model_adj6_input   = (*env)->GetFieldID(env, bigClass, "LR_model_adj6_input", "[D");
            jfieldID LR_model_adj7_input   = (*env)->GetFieldID(env, bigClass, "LR_model_adj7_input", "[D");
            jfieldID LR_model_adj8_input   = (*env)->GetFieldID(env, bigClass, "LR_model_adj8_input", "[D");
            jfieldID LR_model_adj9_input   = (*env)->GetFieldID(env, bigClass, "LR_model_adj9_input", "[D");

                jfieldID weight_model_coeff1   = (*env)->GetFieldID(env, bigClass, "weight_model_coeff1", "[D");
                jfieldID weight_model_coeff2   = (*env)->GetFieldID(env, bigClass, "weight_model_coeff2", "[D");
                jfieldID weight_model_coeff3   = (*env)->GetFieldID(env, bigClass, "weight_model_coeff3", "[D");
                 jfieldID weight_model_coeff4   = (*env)->GetFieldID(env, bigClass, "weight_model_coeff4", "[D");
                jfieldID weight_model_coeff5   = (*env)->GetFieldID(env, bigClass, "weight_model_coeff5", "[D");
                jfieldID weight_model_coeff6   = (*env)->GetFieldID(env, bigClass, "weight_model_coeff6", "[D");
                jfieldID weight_model_coeff7   = (*env)->GetFieldID(env, bigClass, "weight_model_coeff7", "[D");
                jfieldID weight_model_coeff8   = (*env)->GetFieldID(env, bigClass, "weight_model_coeff8", "[D");
                jfieldID weight_model_coeff9   = (*env)->GetFieldID(env, bigClass, "weight_model_coeff9", "[D");




              jdoubleArray sensor = (jdoubleArray)(*env)->GetObjectField(env, csbean, sensor_sel_for_loc);//获取数据

              int  senlend = (*env)->GetArrayLength(env,sensor);
             double *sen_dou = (double *)(*env)->GetDoubleArrayElements(env,sensor, NULL);

               LOGI("******************sensor_sel_for_loc:%d",senlend);
                for(int p6=0;p6<senlend;p6++){
                    st0.sensor_sel_for_loc[p6]=sen_dou[p6];
                }
                 (*env)->ReleaseDoubleArrayElements(env, sensor, sen_dou,0);

            jdoubleArray b_input = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj_stage_bound_input);//获取数据

               int  binput_len = (*env)->GetArrayLength(env,b_input);
               double *binput_d =(double *) (*env)->GetDoubleArrayElements(env,b_input,NULL);
                for(int p5=0;p5<binput_len;p5++){
                       st0.LR_model_adj_stage_bound_input[p5]=binput_d[p5];
                 }

                (*env)->ReleaseDoubleArrayElements(env, b_input, binput_d,0);

             jdoubleArray bound = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj_stage_bound);//获取数据

                 int  bolen = (*env)->GetArrayLength(env,bound);
                  double *bo_dou =(double *) (*env)->GetDoubleArrayElements(env,bound,NULL);
                  for(int p7=0;p7<bolen;p7++){
                        st0.LR_model_adj_stage_bound[p7]=bo_dou[p7];
                  }
                (*env)->ReleaseDoubleArrayElements(env, bound, bo_dou,0);


            jdoubleArray sensors1 = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj_sensors1);//获取数据
                     int  s1_len = (*env)->GetArrayLength(env,sensors1);
                    double *s1_dou = (double *)(*env)->GetDoubleArrayElements(env,sensors1, NULL);

                       for(int s1=0;s1<s1_len;s1++){
                         st0.LR_model_adj_sensors1[s1]=s1_dou[s1];
                    }
                    (*env)->ReleaseDoubleArrayElements(env, sensors1, s1_dou,0);

            jdoubleArray sensors2 = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj_sensors2);//获取数据
                     int  s2_len = (*env)->GetArrayLength(env,sensors2);
                     double *s2_dou = (double *)(*env)->GetDoubleArrayElements(env,sensors2, NULL);
                     //memcpy(st0.LR_model_adj_sensors2, s2_dou, s2_len);
                    LOGI("******************LR_model_adj_sensors2:%d",s2_len);

                        for(int b=0;b<s2_len;b++){
                            LOGI("java...LR_model_adj_sensors2==%f",s2_dou[b]);
                            st0.LR_model_adj_sensors2[b]=s2_dou[b];
                           LOGI("object...LR_model_adj_sensors2==%f",st0.LR_model_adj_sensors2[b]);
                       }
                       (*env)->ReleaseDoubleArrayElements(env, sensors2, s2_dou,0);

            jdoubleArray sensors3 = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj_sensors3);//获取数据
              int  s3_len =(*env)->GetArrayLength(env,sensors3);
               double *s3_dou = (double *)(*env)->GetDoubleArrayElements(env,sensors3, NULL);
               for(int s3=0;s3<s3_len;s3++){
                    st0.LR_model_adj_sensors3[s3]=s3_dou[s3];
                }
                   (*env)->ReleaseDoubleArrayElements(env, sensors3, s3_dou,0);

            jdoubleArray sensors4 = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj_sensors4);//获取数据
              int  s4_len =(*env)->GetArrayLength(env,sensors4);
               double *s4_dou = (double *)(*env)->GetDoubleArrayElements(env,sensors4, NULL);

               for(int s4=0;s4<s4_len;s4++){
                   st0.LR_model_adj_sensors4[s4]=s4_dou[s4];
              }
               (*env)->ReleaseDoubleArrayElements(env, sensors4, s4_dou,0);

            jdoubleArray sensors5 = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj_sensors5);//获取数据
                 int  s5_len = (*env)->GetArrayLength(env,sensors5);
                  double *s5_dou = (double *)(*env)->GetDoubleArrayElements(env,sensors5, NULL);

               for(int s5=0;s5<s5_len;s5++){
                  st0.LR_model_adj_sensors5[s5]=s5_dou[s5];
              }
               (*env)->ReleaseDoubleArrayElements(env, sensors5, s5_dou,0);

            jdoubleArray sensors6 = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj_sensors6);//获取数据
                         int  s6_len =(*env)->GetArrayLength(env,sensors6);
                          double *s6_dou = (double *)(*env)->GetDoubleArrayElements(env,sensors6, NULL);
                     for(int s6=0;s6<s6_len;s6++){
                        st0.LR_model_adj_sensors6[s6]=s6_dou[s6];
                   }
                   (*env)->ReleaseDoubleArrayElements(env, sensors6, s6_dou,0);

            jdoubleArray sensors7 = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj_sensors7);//获取数据
                     int  s7_len = (*env)->GetArrayLength(env,sensors7);
                       double *s7_dou = (double *)(*env)->GetDoubleArrayElements(env,sensors7,NULL);
                       for(int s7=0;s7<s7_len;s7++){
                          st0.LR_model_adj_sensors7[s7]=s7_dou[s7];
                   }
                    (*env)->ReleaseDoubleArrayElements(env, sensors7, s7_dou,0);


            jdoubleArray sensors8 = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj_sensors8);//获取数据
                      int  s8_len =(*env)->GetArrayLength(env,sensors8);
                         double *s8_dou = (double *)(*env)->GetDoubleArrayElements(env,sensors8, NULL);
                      for(int s8=0;s8<s8_len;s8++){
                             st0.LR_model_adj_sensors8[s8]=s8_dou[s8];
                       }
                     (*env)->ReleaseDoubleArrayElements(env, sensors8, s8_dou,0);


            jdoubleArray sensors9 = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj_sensors9);//获取数据
                    int  s9_len = (*env)->GetArrayLength(env,sensors9);
                     double *s9_dou = (double *)(*env)->GetDoubleArrayElements(env,sensors9, NULL);
                    for(int s9=0;s9<s9_len;s9++){
                       st0.LR_model_adj_sensors9[s9]=s9_dou[s9];
                   }
                  (*env)->ReleaseDoubleArrayElements(env, sensors9, s9_dou,0);

            jdoubleArray adj1 = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj1_input);//获取数据
                            int  a1_len =(*env)->GetArrayLength(env,adj1);
                                 double *a1_dou = (double *)(*env)->GetDoubleArrayElements(env,adj1, NULL);
                      for(int d1=0;d1<a1_len;d1++){
                               st0.LR_model_adj1_input[d1]=a1_dou[d1];
                          }
                           (*env)->ReleaseDoubleArrayElements(env, adj1, a1_dou,0);

            jdoubleArray adj2 = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj2_input);//获取数据
                            int  a2_len = (*env)->GetArrayLength(env,adj2);
                                 double *a2_dou =(double *) (*env)->GetDoubleArrayElements(env,adj2, NULL);
                      for(int d2=0;d2<a2_len;d2++){
                              st0.LR_model_adj2_input[d2]=a2_dou[d2];
                      }
                 (*env)->ReleaseDoubleArrayElements(env, adj2, a2_dou,0);

            jdoubleArray adj3 = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj3_input);//获取数据
                             int  a3_len = (*env)->GetArrayLength(env,adj3);
                                 double *a3_dou = (double *)(*env)->GetDoubleArrayElements(env,adj3,NULL);
                     for(int d3=0;d3<a3_len;d3++){
                            st0.LR_model_adj3_input[d3]=a3_dou[d3];
                      }
                (*env)->ReleaseDoubleArrayElements(env, adj3, a3_dou,0);

            jdoubleArray adj4 = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj4_input);//获取数据
                             int  a4_len =(*env)->GetArrayLength(env,adj4);
                              double *a4_dou =(double *) (*env)->GetDoubleArrayElements(env,adj4,NULL);
                    LOGI("******************LR_model_adj4_input:%d",a4_len);

                       for(int a=0;a<a4_len;a++){
                       st0.LR_model_adj4_input[a]=a4_dou[a];
                           LOGI("java...LR_model_adj4_input==%f",a4_dou[a]);
                           LOGI("object...LR_model_adj4_input==%f",st0.LR_model_adj4_input[a]);
                       }
                 (*env)->ReleaseDoubleArrayElements(env, adj4, a4_dou,0);

            jdoubleArray adj5 = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj5_input);//获取数据
                        int  a5_len =(*env)->GetArrayLength(env,adj5);
                      double *a5_dou =(double *) (*env)->GetDoubleArrayElements(env,adj5, NULL);

                      for(int d5=0;d5<a5_len;d5++){
                                     st0.LR_model_adj5_input[d5]=a5_dou[d5];
                       }
                      (*env)->ReleaseDoubleArrayElements(env, adj5, a5_dou,0);

            jdoubleArray adj6 = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj6_input);//获取数据
                     int  a6_len = (*env)->GetArrayLength(env,adj6);
                      double *a6_dou = (double *)(*env)->GetDoubleArrayElements(env,adj6,NULL);
                 for(int d6=0;d6<a6_len;d6++){
                          st0.LR_model_adj6_input[d6]=a6_dou[d6];
                }
                (*env)->ReleaseDoubleArrayElements(env, adj6, a6_dou,0);

            jdoubleArray adj7 = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj7_input);//获取数据
                             int  a7_len = (*env)->GetArrayLength(env,adj7);
                               double *a7_dou = (double *)(*env)->GetDoubleArrayElements(env,adj7, NULL);
                for(int d7=0;d7<a7_len;d7++){
                        st0.LR_model_adj7_input[d7]=a7_dou[d7];
                 }
                  (*env)->ReleaseDoubleArrayElements(env, adj7, a7_dou,0);

            jdoubleArray adj8= (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj8_input);//获取数据
                   int  a8_len = (*env)->GetArrayLength(env,adj8);
                      double *a8_dou = (double *)(*env)->GetDoubleArrayElements(env,adj8, NULL);
                 for(int d8=0;d8<a8_len;d8++){
                         st0.LR_model_adj8_input[d8]=a8_dou[d8];
                  }

                  (*env)->ReleaseDoubleArrayElements(env, adj8, a8_dou,0);

            jdoubleArray adj9 = (jdoubleArray)(*env)->GetObjectField(env, csbean, LR_model_adj9_input);//获取数据
                         int  a9_len = (*env)->GetArrayLength(env,adj9);
                            double *a9_dou = (double *)(*env)->GetDoubleArrayElements(env,adj9,NULL);
                 for(int d9=0;d9<a9_len;d9++){
                        st0.LR_model_adj9_input[d9]=a9_dou[d9];
                  }
                    (*env)->ReleaseDoubleArrayElements(env, adj9, a9_dou,0);

                jdoubleArray coeff1 = (jdoubleArray)(*env)->GetObjectField(env, csbean, weight_model_coeff1);//获取数据
                             int  c1_len = (*env)->GetArrayLength(env,coeff1);
                              double *c1_dou =(double *) (*env)->GetDoubleArrayElements(env,coeff1,NULL);

                                   for(int c1=0;c1<c1_len;c1++){
                                        st0.weight_model_coeff1[c1]=c1_dou[c1];
                                  }
                        (*env)->ReleaseDoubleArrayElements(env, coeff1, c1_dou,0);

                jdoubleArray coeff2 = (jdoubleArray)(*env)->GetObjectField(env, csbean, weight_model_coeff2);//获取数据
                            int  c2_len = (*env)->GetArrayLength(env,coeff2);
                             double *c2_dou =(double *) (*env)->GetDoubleArrayElements(env,coeff2,NULL);
                             for(int c2=0;c2<c2_len;c2++){
                                            st0.weight_model_coeff2[c2]=c2_dou[c2];
                                 }
                     (*env)->ReleaseDoubleArrayElements(env, coeff2, c2_dou,0);


                jdoubleArray coeff3 = (jdoubleArray)(*env)->GetObjectField(env, csbean, weight_model_coeff3);//获取数据
                             int  c3_len = (*env)->GetArrayLength(env,coeff3);
                            double *c3_dou = (double *)(*env)->GetDoubleArrayElements(env,coeff3, NULL);
                             for(int c3=0;c3<c3_len;c3++){
                                   st0.weight_model_coeff3[c3]=c3_dou[c3];
                            }
                    (*env)->ReleaseDoubleArrayElements(env, coeff3, c3_dou,0);


                jdoubleArray coeff4 = (jdoubleArray)(*env)->GetObjectField(env, csbean, weight_model_coeff4);//获取数据
                            int  c4_len = (*env)->GetArrayLength(env,coeff4);
                               double *c4_dou = (double *)(*env)->GetDoubleArrayElements(env,coeff4,NULL);

                             for(int c4=0;c4<c4_len;c4++){
                                      st0.weight_model_coeff4[c4]=c4_dou[c4];
                               }
                (*env)->ReleaseDoubleArrayElements(env, coeff4, c4_dou,0);


                 jdoubleArray coeff5 = (jdoubleArray)(*env)->GetObjectField(env, csbean, weight_model_coeff5);//获取数据
                             int  c5_len = (*env)->GetArrayLength(env,coeff5);
                             double *c5_dou = (double *)(*env)->GetDoubleArrayElements(env,coeff5, NULL);
                             for(int c5=0;c5<c5_len;c5++){
                                     st0.weight_model_coeff5[c5]=c5_dou[c5];
                            }
                      (*env)->ReleaseDoubleArrayElements(env, coeff5, c5_dou,0);



                 jdoubleArray coeff6 = (jdoubleArray)(*env)->GetObjectField(env, csbean, weight_model_coeff6);//获取数据
                                int  c6_len = (*env)->GetArrayLength(env,coeff6);
                                  double *c6_dou =(double *) (*env)->GetDoubleArrayElements(env,coeff6, NULL);
                        LOGI("******************weight_model_coeff6:%d",c6_len);

                          for(int c6=0;c6<c6_len;c6++){
                                st0.weight_model_coeff6[c6]=c6_dou[c6];
                             }

                  (*env)->ReleaseDoubleArrayElements(env, coeff6, c6_dou,0);


                jdoubleArray coeff7 = (jdoubleArray)(*env)->GetObjectField(env, csbean, weight_model_coeff7);//获取数据
                                int  c7_len = (*env)->GetArrayLength(env,coeff7);
                                  double *c7_dou = (double *)(*env)->GetDoubleArrayElements(env,coeff7,NULL);
                                 for(int c7=0;c7<c7_len;c7++){
                                         st0.weight_model_coeff7[c7]=c7_dou[c7];
                                 }
                (*env)->ReleaseDoubleArrayElements(env, coeff7, c7_dou,0);
                  LOGI("******************weight_model_coeff7:%d",c7_len);

                 jdoubleArray coeff8= (jdoubleArray)(*env)->GetObjectField(env, csbean, weight_model_coeff8);//获取数据
                                int  c8_len = (*env)->GetArrayLength(env,coeff8);
                              double *c8_dou =(double *) (*env)->GetDoubleArrayElements(env,coeff8, NULL);
                              for(int c8=0;c8<c8_len;c8++){
                                      st0.weight_model_coeff8[c8]=c8_dou[c8];
                              }
                    (*env)->ReleaseDoubleArrayElements(env, coeff8, c8_dou,0);
                     LOGI("******************weight_model_coeff8:%d",c8_len);

                jdoubleArray coeff9 = (jdoubleArray)(*env)->GetObjectField(env, csbean, weight_model_coeff9);//获取数据
                                int  c9_len = (*env)->GetArrayLength(env,coeff9);
                               double *c9_dou = (double *)(*env)->GetDoubleArrayElements(env,coeff9, NULL);

                                  for(int c9=0;c9<c9_len;c9++){
                                       st0.weight_model_coeff9[c9]=c9_dou[c9];
                                   }
                               (*env)->ReleaseDoubleArrayElements(env, coeff9, c9_dou,0);
                                LOGI("******************weight_model_coeff9:%d",c9_len);

                    //st0.KNN_Model=st1;
                    //memcpy((void*)&st0.KNN_Model,(void*)&st1,sizeof(struct1_T));
                    st1_to_st0(&st0,&st1);//给机构体赋值 会有问题 注意
                    LOGI("******************st0.KNN_Model:@@@@@@@@@");

                 double last_data_test[42]={last_data1,last_data2,last_data3,last_data4,last_data5,last_data6,last_data7,last_data8,last_data9,last_data10,last_data11,last_data12,last_data13,last_data14,last_data15,last_data16,last_data17,last_data18,last_data19,last_data20,last_data21,last_data22,last_data23,last_data24
                        ,last_data25,last_data26,last_data27,last_data28,last_data29,last_data30,last_data31,last_data32,last_data33
                        ,last_data34,last_data35,last_data36,last_data37,last_data38,last_data39,last_data40,last_data41,last_data42};
                stableWeightPredict_initialize();

                    LOGI("last_data_test");
            double getDat[46]={0};
            double *weight=stableWeightPredict(arr_Sensor_data,clear_flag,last_data_test,&status_flag,&locked_weight,&stable_counter,&last_weight,&st0,getDat);
                  for(int i=0;i<42;i++){
                      LOGI("weight[%d]==%f\r\n",i,weight[i]);
                 }
                //赋值
               last_weight =*(weight+0);
               status_flag=*(weight+1);
               locked_weight=*(weight+2);
                stable_counter=*(weight+3);
                        last_data1=*(weight+4);
                        last_data2=*(weight+5);
                        last_data3=*(weight+6);
                       last_data4=*(weight+7);
                        last_data5=*(weight+8);
                        last_data6=*(weight+9);
                        last_data7=*(weight+10);
                        last_data8=*(weight+11);
                        last_data9=*(weight+12);
                        last_data10=*(weight+13);
                        last_data11=*(weight+14);
                        last_data12=*(weight+15);
                        last_data13=*(weight+16);
                        last_data14=*(weight+17);
                        last_data15=*(weight+18);
                        last_data16=*(weight+19);
                        last_data17=*(weight+20);
                        last_data18=*(weight+21);
                        last_data19=*(weight+22);
                        last_data20=*(weight+23);
                        last_data21=*(weight+24);
                        last_data22=*(weight+25);
                        last_data23=*(weight+26);
                        last_data24=*(weight+27);
                         last_data25=*(weight+28);
                         last_data26=*(weight+29);
                         last_data27=*(weight+30);
                         last_data28=*(weight+31);
                         last_data29=*(weight+32);
                         last_data30=*(weight+33);
                         last_data31=*(weight+34);
                         last_data32=*(weight+35);
                         last_data33=*(weight+36);
                         last_data34=*(weight+37);
                         last_data35=*(weight+38);
                         last_data36=*(weight+39);
                         last_data37=*(weight+40);
                         last_data38=*(weight+41);
                         last_data39=*(weight+42);
                         last_data40=*(weight+43);
                         last_data41=*(weight+44);
                         last_data42=*(weight+45);

               // for(int i=0;i<42;i++){
                 //   LOGI("last_data_test==%f",last_data_test[i]);
              //  }

               stableWeightPredict_terminate();

            return last_weight;



  };

#ifdef __cplusplus
}
#endif
#endif
